# Generated by Django 4.0.3 on 2022-04-10 03:56

from django.db import migrations, models
import music_upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('artist', models.CharField(max_length=60)),
                ('file', models.FileField(upload_to='C:\\Users\\user\\Downloads\\Github\\djangoProject\\music\\<django.db.models.fields.CharField>', validators=[music_upload.models.validate_file_extension])),
            ],
        ),
    ]
