# Generated by Django 4.0.3 on 2022-04-16 20:03

from django.db import migrations, models
import music_upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('music_upload', '0002_remove_music_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='id',
        ),
        migrations.AlterField(
            model_name='music',
            name='file',
            field=models.FileField(upload_to='C:\\Users\\user\\Downloads\\Github\\djangoProject\\music', validators=[music_upload.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
